/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opennms_protocols_icmp_IcmpSocket */

#ifndef _Included_org_opennms_protocols_icmp_IcmpSocket
#define _Included_org_opennms_protocols_icmp_IcmpSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opennms_protocols_icmp_IcmpSocket
 * Method:    initSocket
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_opennms_protocols_icmp_IcmpSocket_initSocket
  (JNIEnv *, jobject);

/*
 * Class:     org_opennms_protocols_icmp_IcmpSocket
 * Method:    receive
 * Signature: ()Ljava/net/DatagramPacket;
 */
JNIEXPORT jobject JNICALL Java_org_opennms_protocols_icmp_IcmpSocket_receive
  (JNIEnv *, jobject);

/*
 * Class:     org_opennms_protocols_icmp_IcmpSocket
 * Method:    send
 * Signature: (Ljava/net/DatagramPacket;)V
 */
JNIEXPORT void JNICALL Java_org_opennms_protocols_icmp_IcmpSocket_send
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_opennms_protocols_icmp_IcmpSocket
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_opennms_protocols_icmp_IcmpSocket_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_opennms_protocols_icmp_IcmpSocket_Logger */

#ifndef _Included_org_opennms_protocols_icmp_IcmpSocket_Logger
#define _Included_org_opennms_protocols_icmp_IcmpSocket_Logger
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
